// src/components/headroom/headroom.tsx
import {
  component$,
  PropFunction,
  Slot,
  useClientEffect$,
  useRef,
  useStore,
} from "@builder.io/qwik";
import CSS from "csstype";
import raf from "raf";
import { shouldUpdate, States } from "./shouldUpdate";
import { supportsPassiveEvents } from "./supportsPassiveEvents";

export interface HeadroomProps {
  className?: string;
  parent$?: PropFunction<() => HTMLElement | Window>;
  //   children: PropTypes.any.isRequired,
  disableInlineStyles?: boolean;
  disable?: boolean;
  pin?: boolean;
  upTolerance?: number;
  downTolerance?: number;
  onPin$?: PropFunction<() => void>;
  onUnpin$?: PropFunction<() => void>;
  onUnfix$?: PropFunction<() => void>;
  wrapperStyle?: CSS.Properties;
  pinStart?: number;
  style?: CSS.Properties;
  calcHeightOnResize?: boolean;
  tag?: keyof HTMLElementTagNameMap;
}

interface HeadroomState {
  state: States;
  translateY: string;
  className: string;
  animation: boolean;
  height: number;
  currentScrollY: number;
  lastKnownScrollY: number;
  scrollTicking: boolean;
  resizeTicking: boolean;
}

export const Headroom = component$((props: HeadroomProps) => {
  const state = useStore<HeadroomState>({
    state: "unfixed",
    translateY: "0",
    className: "headroom headroom--unfixed",
    animation: true,
    height: 0,
    currentScrollY: 0,
    lastKnownScrollY: 0,
    scrollTicking: false,
    resizeTicking: false,
  });
  const ref = useRef<HTMLDivElement>();

  if (props.disable && state.state !== "unfixed") {
    state.translateY = "0";
    state.className = "headroom headroom--unfixed headroom-disable-animation";
    state.animation = false;
    state.state = "unfixed";
  }

  useClientEffect$(async () => {
    const getScrollY = async () => {
      if (props.parent$) {
        const parentElement = await props.parent$();
        if (
          parentElement instanceof Window &&
          parentElement.scrollY !== undefined
        ) {
          return parentElement.scrollY;
        } else if (
          parentElement instanceof HTMLElement &&
          parentElement.scrollTop !== undefined
        ) {
          return parentElement.scrollTop;
        }
      }

      return (
        document.documentElement ||
        document.body.parentNode ||
        document.body
      ).scrollTop;
    };

    const getViewportHeight = () =>
      window.innerHeight ||
      document.documentElement.clientHeight ||
      document.body.clientHeight;

    const getDocumentHeight = () => {
      const body = document.body;
      const documentElement = document.documentElement;

      return Math.max(
        body.scrollHeight,
        documentElement.scrollHeight,
        body.offsetHeight,
        documentElement.offsetHeight,
        body.clientHeight,
        documentElement.clientHeight
      );
    };

    const getElementPhysicalHeight = (elm: HTMLElement) =>
      Math.max(elm.offsetHeight, elm.clientHeight);

    const getElementHeight = (elm: HTMLElement) =>
      Math.max(elm.scrollHeight, elm.offsetHeight, elm.clientHeight);

    const getScrollerPhysicalHeight = async () => {
      if (!props.parent$) return getViewportHeight();
      const parentElement = await props.parent$();

      return parentElement === window || parentElement === document.body
        ? getViewportHeight()
        : getElementPhysicalHeight(parentElement as HTMLElement);
    };

    const getScrollerHeight = async () => {
      if (!props.parent$) return getDocumentHeight();

      const parentElement = await props.parent$();

      return parentElement === window || parentElement === document.body
        ? getDocumentHeight()
        : getElementHeight(parentElement as HTMLElement);
    };

    const isOutOfBound = async (currentScrollY: number) => {
      const pastTop = currentScrollY < 0;

      const scrollerPhysicalHeight = await getScrollerPhysicalHeight();
      const scrollerHeight = await getScrollerHeight();

      const pastBottom =
        currentScrollY + scrollerPhysicalHeight > scrollerHeight;

      return pastTop || pastBottom;
    };

    const unpin = () => {
      if (props.onUnpin$) props.onUnpin$();

      state.translateY = "-100%";
      state.className = "headroom headroom--unpinned";
      state.animation = true;
      state.state = "unpinned";
    };

    const unpinSnap = () => {
      if (props.onUnpin$) props.onUnpin$();

      state.translateY = "-100%";
      state.className =
        "headroom headroom--unpinned headroom-disable-animation";
      state.animation = false;
      state.state = "unpinned";
    };

    const pin = () => {
      if (props.onPin$) props.onPin$();

      state.translateY = "0";
      state.className = "headroom headroom--pinned";
      state.animation = true;
      state.state = "pinned";
    };

    const unfix = () => {
      if (props.onUnfix$) props.onUnfix$();
      state.translateY = "0";
      state.className = "headroom headroom--unfixed headroom-disable-animation";
      state.animation = false;
      Promise.resolve().then(() => {
        state.state = "unfixed";
      });
    };

    const update = async () => {
      state.currentScrollY = await getScrollY();

      const outOfBounds = await isOutOfBound(state.currentScrollY);
      if (!outOfBounds) {
        const { action } = shouldUpdate(
          state.lastKnownScrollY,
          state.currentScrollY,
          props,
          state
        );

        if (action === "pin") {
          pin();
        } else if (action === "unpin") {
          unpin();
        } else if (action === "unpin-snap") {
          unpinSnap();
        } else if (action === "unfix") {
          unfix();
        }
      }

      state.lastKnownScrollY = state.currentScrollY;
      state.scrollTicking = false;
    };

    const setHeightOffset = () => {
      state.height = ref.current?.offsetHeight || 0;
      state.resizeTicking = false;
    };
    setHeightOffset();

    const eventListenerOptions = supportsPassiveEvents()
      ? { passive: true, capture: false }
      : false;

    if (props.disable) return;

    const parentElement = (await props.parent$?.()) || window;

    const handleScroll = () => {
      if (!state.scrollTicking) {
        state.scrollTicking = true;
        raf(update);
      }
    };

    const handleResize = () => {
      if (!state.resizeTicking) {
        state.resizeTicking = true;
        raf(setHeightOffset);
      }
    };

    parentElement.addEventListener(
      "scroll",
      handleScroll,
      eventListenerOptions
    );

    if (props.calcHeightOnResize) {
      parentElement.addEventListener(
        "resize",
        handleResize,
        eventListenerOptions
      );
    }

    return () => {
      parentElement.removeEventListener(
        "scroll",
        handleScroll,
        eventListenerOptions
      );
      parentElement.removeEventListener(
        "resize",
        handleResize,
        eventListenerOptions
      );
    };
  });

  const Tag: keyof HTMLElementTagNameMap = props.tag || "div";

  let innerStyle: CSS.Properties = {
    position: props.disable || state.state === "unfixed" ? "relative" : "fixed",
    top: "0",
    left: "0",
    right: "0",
    zIndex: "1",
    WebkitTransform: `translate3D(0, ${state.translateY}, 0)`,
    msTransform: `translate3D(0, ${state.translateY}, 0)`,
    transform: `translate3D(0, ${state.translateY}, 0)`,
  };

  let className = state.className;

  // Don't add css transitions until after we've done the initial
  // negative transform when transitioning from 'unfixed' to 'unpinned'.
  // If we don't do this, the header will flash into view temporarily
  // while it transitions from 0 — -100%.
  if (state.animation) {
    innerStyle = {
      ...innerStyle,
      WebkitTransition: "all .2s ease-in-out",
      MozTransition: "all .2s ease-in-out",
      OTransition: "all .2s ease-in-out",
      transition: "all .2s ease-in-out",
    };
    className += " headroom--scrolled";
  }

  if (!props.disableInlineStyles) {
    innerStyle = {
      ...innerStyle,
      ...props.style,
    };
  } else {
    innerStyle = props.style || {};
  }

  const wrapperStyles = {
    ...props.wrapperStyle,
    height: state.height ? `${state.height}px` : null,
  };

  const wrapperClassName = props.className
    ? `${props.className} headroom-wrapper`
    : "headroom-wrapper";

  return (
    <Tag
      style={wrapperStyles as Record<string, string | number>}
      className={wrapperClassName}
    >
      <div
        ref={ref}
        style={innerStyle as Record<string, string | number>}
        className={className}
      >
        <Slot />
      </div>
    </Tag>
  );
});

// components/headroom/Headroom.vue
<template>
	<div :style="{ height: data.height + 'px' }">
		<div :class="cls" :style="style">
			<slot ref="slotRef"></slot>
		</div>
	</div>
</template>

<script setup lang="ts">
import raf from "raf";
import checkActions, { HeadroomData } from "./checkActions";
import { defaultClasses } from "./defaultClasses";
import support3d from "./support3d";

const props = defineProps({
	scroller: {
		type: Function,
		default: () => window,
	},
	disabled: {
		type: Boolean,
		default: false,
	},
	upTolerance: {
		type: Number,
		default: 5,
	},
	downTolerance: {
		type: Number,
		default: 0,
	},
	speed: {
		type: Number,
		default: 250,
	},
	easing: {
		type: String,
		default: "ease-in-out",
	},
	zIndex: {
		type: Number,
		default: 9999,
	},
	offset: {
		type: Number,
		default: 0,
	},
	classes: {
		type: Object,
		default: () => defaultClasses,
	},
	footroom: {
		type: Boolean,
		default: false,
	},
});

const emit = defineEmits([
	"top",
	"not-top",
	"bottom",
	"not-bottom",
	"fix",
	"unfix",
	"pin",
	"unpin",
]);

const data = reactive<HeadroomData>({
	isTop: false,
	isNotTop: false,
	isBottom: false,
	isNotBottom: false,
	isPinned: false,
	isUnpinned: false,
	currentScrollY: 0,
	lastScrollY: 0,
	state: "unfixed",
	translate: 0,
	height: "",
	animation: true,
	isSupport3d: false,
});
const slotRef = ref<HTMLElement | null>(null);

const style = computed(() => {
	let styles: Record<string, string | number> = {
		position: props.disabled || data.state === "unfixed" ? "relative" : "fixed",
		top: "0",
		left: "0",
		right: "0",
		"z-index": props.zIndex,
	};

	if (props.footroom) {
		styles = { ...styles, top: "unset", bottom: "0" };
	}

	// SSR cannot detect scroll position. To prevent flash when component mounted,
	// just add transition styles in browser.
	if (!process.server) {
		styles.transform = data.isSupport3d
			? `translate3d(0, ${data.translate}, 0)`
			: `translateY(${data.translate})`;

		if (data.animation) {
			styles.transition = `all ${props.speed}ms ${props.easing}`;
		}
	}

	return styles;
});

const clsOpts = computed(() => {
	return {
		...defaultClasses,
		...props.classes,
	};
});

const cls = computed(() => {
	let cls = clsOpts.value;
	return props.disabled
		? {}
		: {
				[cls.top]: data.isTop,
				[cls.notTop]: data.isNotTop,
				[cls.bottom]: data.isBottom,
				[cls.notBottom]: data.isNotBottom,
				[cls.pinned]: data.isPinned,
				[cls.unpinned]: data.isUnpinned,
				[cls.initial]: true,
		  };
});

const getViewportHeight = () => {
	return (
		window.innerHeight ||
		document.documentElement.clientHeight ||
		document.body.clientHeight
	);
};

const getElementPhysicalHeight = (elm: HTMLElement) =>
	Math.max(elm.offsetHeight, elm.clientHeight);

const getDocumentHeight = () => {
	const body = document.body;
	const documentElement = document.documentElement;

	return Math.max(
		body.scrollHeight,
		documentElement.scrollHeight,
		body.offsetHeight,
		documentElement.offsetHeight,
		body.clientHeight,
		documentElement.clientHeight
	);
};

const getElementHeight = (elm: HTMLElement) =>
	Math.max(elm.scrollHeight, elm.offsetHeight, elm.clientHeight);

const getScrollerPhysicalHeight = () => {
	const parent = props.scroller();

	return parent === window || parent === document.body
		? getViewportHeight()
		: getElementPhysicalHeight(parent);
};

const getScrollerHeight = () => {
	const parent = props.scroller();

	return parent === window || parent === document.body
		? getDocumentHeight()
		: getElementHeight(parent);
};

const isOutOfBound = (currentScrollY: number) => {
	const pastTop = currentScrollY < 0;

	const scrollerPhysicalHeight = getScrollerPhysicalHeight();
	const scrollerHeight = getScrollerHeight();

	const pastBottom = currentScrollY + scrollerPhysicalHeight > scrollerHeight;

	return pastTop || pastBottom;
};

const handleScroll = () => {
	raf(update);
};

const setHeightOffset = () => {
	data.height = slotRef.value
		? slotRef.value.children[0] &&
		  (slotRef.value.firstElementChild as HTMLElement)?.offsetHeight
		: "";
};

const getScrollY = () => {
	let top;
	if (props.scroller().pageYOffset !== undefined) {
		top = props.scroller().pageYOffset;
	} else if (props.scroller().scrollTop !== undefined) {
		top = props.scroller().scrollTop;
	} else {
		top = (
			document.documentElement ||
			document.body.parentNode ||
			document.body
		).scrollTop;
	}
	return top;
};

const update = () => {
	data.currentScrollY = getScrollY();

	if (isOutOfBound(data.currentScrollY)) {
		return;
	}

	if (data.currentScrollY <= props.offset) {
		top();
	} else {
		notTop();
	}

	if (data.currentScrollY + getViewportHeight() >= getScrollerHeight()) {
		bottom();
	} else {
		notBottom();
	}

	const action = checkActions(data, props);

	if (action === "pin") {
		pin();
	} else if (action === "unpin-snap") {
		unpinSnap();
	} else if (action === "unpin") {
		unpin();
	} else if (action === "unfix") {
		unfix();
	}

	data.lastScrollY = data.currentScrollY;
};

const top = () => {
	data.isTop = true;
	data.isNotTop = false;
	emit("top");
};

const notTop = () => {
	data.isTop = false;
	data.isNotTop = true;
	emit("not-top");
};

const bottom = () => {
	data.isBottom = true;
	data.isNotBottom = false;
	emit("bottom");
};

const notBottom = () => {
	data.isNotBottom = true;
	data.isBottom = false;
	emit("not-bottom");
};

const pin = () => {
	data.isPinned = true;
	data.isUnpinned = false;
	data.animation = true;
	emit("pin");
	data.translate = 0;
	nextTick(() => {
		data.state = "pinned";
	});
};

const unpin = () => {
	data.isUnpinned = true;
	data.isPinned = false;
	data.animation = true;
	emit("unpin");
	data.translate = props.footroom ? "100%" : "-100%";
	nextTick(() => {
		data.state = "unpinned";
	});
};

const unpinSnap = () => {
	data.isUnpinned = true;
	data.isPinned = false;
	data.animation = false;
	emit("unpin");
	data.translate = props.footroom ? "100%" : "-100%";
	nextTick(() => {
		data.state = "unpinned";
	});
};

const unfix = () => {
	data.translate = 0;
	data.animation = false;
	emit("unfix");
	nextTick(() => {
		data.state = "unfixed";
	});
};

watch(
	() => props.disabled,
	(newVal) => {
		if (newVal) {
			props.scroller().removeEventListener("scroll", handleScroll);
		} else {
			props.scroller().addEventListener("scroll", handleScroll);
		}
	}
);

onMounted(() => {
	data.isSupport3d = support3d();
	setHeightOffset();

	if (!props.disabled) {
		props.scroller().addEventListener("scroll", handleScroll);
	}

	// When headroom is mounted, call handleScroll to set initial state.
	handleScroll();
});

onUpdated(() => {
	nextTick(setHeightOffset);
});

onBeforeUnmount(() => {
	props.scroller().removeEventListener("scroll", handleScroll);
});
</script>
